production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: database_name
 pool: 5
 username: database_user_name
 password: database_user_password
 socket: mysql socket path (/var/mysql/mysql.sock)
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: database_name
 pool: 5
 username: database_user_name
 password: database_user_password
 socket: mysql socket path (/var/mysql/mysql.sock)